---
- hosts: all
  remote_user: root
  sudo: no
  gather_facts: yes

  roles:
     - common

  # tasks:
  #   - name: Final greeting upon successful Completion.
  #     pause: prompt="If you've got this far without any errors everything is probably okay! Press [Enter] to continue."
  #   - name: rebooting
  #     sudo: yes
  #     action: command /sbin/reboot -t now
