"""
Django settings for catmap project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9!ceu3zg_jrqqkccn+ilfd!t^kfjsk-hg#!a+ii^ue-oi$+gd8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TEMPLATE_DEBUG = DEBUG
TEST_PREPROD = False

ALLOWED_HOSTS = ['*']


# Application definition

DJANGO_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

APPLICATION_APPS = (
    'catmap.apps.cat',
    'catmap.apps.shelter',
    'catmap.apps.dashboard',
)

HELPER_APPS = (
    'pipeline',
    'corsheaders',
    'djangobower',
    'crispy_forms',
    'pinax.eventlog',
    'django_extensions',
    'rest_framework',
    'import_export',
)


INSTALLED_APPS = DJANGO_APPS + HELPER_APPS + APPLICATION_APPS

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'pipeline.middleware.MinifyHTMLMiddleware',
    'django.middleware.gzip.GZipMiddleware',
)

ROOT_URLCONF = 'catmap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'catmap.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder',
    'pipeline.finders.PipelineFinder',
)

STATICFILES_STORAGE = 'pipeline.storage.PipelineStorage'

BOWER_COMPONENTS_ROOT = BASE_DIR

STATICFILES_DIRS = (
    os.path.join(BOWER_COMPONENTS_ROOT, 'bower_components'),
)

BOWER_INSTALLED_APPS = (
    'angularjs',
    'angular-osm',
    'angular-chart.js',
    'angular-resource',
    'angular-ui-router',
    'angular-moment',
    'moment',
    'angular-smart-table',
    'angular-loading-bar',
    'angular-rangeslider',
    'angular-daterangepicker',
    'bootstrap-daterangepicker',
)

PIPELINE_JS = {
    'dashboard': {
        'source_filenames': (
            # support
            'jquery/dist/jquery.js',
            'bootstrap/dist/js/bootstrap.js',
            # angular
            'angular/angular.js',
            'angular-ui-router/release/angular-ui-router.js',
            'angular-resource/angular-resource.js',
            # moment timestamps
            'moment/moment.js',
            'angular-moment/angular-moment.js',
            # loading bar
            'angular-loading-bar/build/loading-bar.js',
            # range slider
            #'angular-rangeslider/angular.rangeSlider.js',
            # daterange picker
            'bootstrap-daterangepicker/daterangepicker.js',
            'angular-daterangepicker/js/angular-daterangepicker.js',
            # table
            'angular-smart-table/dist/smart-table.js',
            # charts
            'Chart.js/Chart.js',
            'angular-chart.js/dist/angular-chart.js',
            # osm
            'angular-osm/dist/osm.js',
            'angular-base64/angular-base64.js'
            'ngstorage/ngStorage.js.js'
            'osmtogeojson/osmtogeojson.js',
            # The dashboard app
            'js/dashboard.app.js',
        ),
        'output_filename': 'js/dashboard.js',
    },
}

PIPELINE_CSS = {
    'dashboard': {
        'source_filenames': (
            'bootstrap/dist/css/bootstrap.css',
            # chart
            'angular-chart.js/dist/angular-chart.css',
            # loading bar
            'angular-loading-bar/build/loading-bar.css',
            # range slider
            #'angular-rangeslider/angular.rangeSlider.css',
            'bootstrap-daterangepicker/daterangepicker.css',
        ),
        'output_filename': 'css/dashboard.css',
    },
}

PIPELINE_COMPILERS = (
    'pipeline.compilers.less.LessCompiler',
    'pipeline.compilers.sass.SASSCompiler',
)

PIPELINE_JS_COMPRESSOR = 'pipeline.compressors.jsmin.JSMinCompressor'
PIPELINE_CSS_COMPRESSOR = 'pipeline.compressors.csstidy.CSSMinCompressor'

DJANGO_ENV = os.getenv('DJANGO_ENV', os.getenv('RAILS_ENV', 'development'))

#
# Load the environment specific settings
#
try:
    env_path = os.path.join(BASE_DIR, 'config/environments/{DJANGO_ENV}/catmap/local_settings.py'.format(DJANGO_ENV=DJANGO_ENV))
    environment_settings = open(env_path)
    exec(environment_settings)
except Exception as e:
    pass


from .local_settings import *
